<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
    </parent>

    <groupId>com.xcz.commons</groupId>
    <artifactId>commons</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>commons</name>
    <description>公共基础模块</description>
    <packaging>pom</packaging>

    <modules>
        <module>commons-core</module>
        <module>commons-log</module>
        <module>commons-oss</module>
        <module>commons-security</module>
        <module>commons-redis</module>
        <module>commons-database</module>
        <module>commons-mongodb</module>
        <module>commons-protobuf</module>
        <module>commons-excel</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <lombok.version>1.18.46</lombok.version>
        <poi.version>5.2.5</poi.version>
        <commons.fileupload.version>1.5</commons.fileupload.version>
        <fastjson.version>2.0.52</fastjson.version>
        <jjwt.version>0.12.6</jjwt.version>
        <commons.io.version>2.11.0</commons.io.version>
        <mybatis-plus.version>3.5.9</mybatis-plus.version>
        <mybatis-plus-generator.version>3.5.2</mybatis-plus-generator.version>
        <alibaba.druid.version>1.2.23</alibaba.druid.version>
        <mysql-connector-j.version>8.0.31</mysql-connector-j.version>
        <durid.version>4.3.1</durid.version>
        <redission.version>3.50.0</redission.version>
        <ip2region.version>3.3.4</ip2region.version>
        <user-agent-utils.version>1.21</user-agent-utils.version>
        <aliyun-oss.version>3.17.4</aliyun-oss.version>
        <spring-cloud.version>2023.0.0</spring-cloud.version>
        <protobuf.version>3.25.5</protobuf.version>
        <reflections.version>0.10.2</reflections.version>
        <excel.version>4.0.3</excel.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- 内部模块版本统一管理 -->
            <dependency>
                <groupId>com.xcz.commons</groupId>
                <artifactId>commons-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.xcz.commons</groupId>
                <artifactId>commons-log</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.xcz.commons</groupId>
                <artifactId>commons-oss</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.xcz.commons</groupId>
                <artifactId>commons-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.xcz.commons</groupId>
                <artifactId>commons-security</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.xcz.commons</groupId>
                <artifactId>commons-database</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.xcz.commons</groupId>
                <artifactId>commons-mongodb</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.xcz.commons</groupId>
                <artifactId>commons-protobuf</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>${protobuf.version}</version>
            </dependency>

            <dependency>
                <groupId>org.reflections</groupId>
                <artifactId>reflections</artifactId>
                <version>${reflections.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>

            <dependency>
                <groupId>org.lionsoul</groupId>
                <artifactId>ip2region</artifactId>
                <version>${ip2region.version}</version>
            </dependency>

            <dependency>
                <groupId>eu.bitwalker</groupId>
                <artifactId>UserAgentUtils</artifactId>
                <version>${user-agent-utils.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons.io.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-fileupload</groupId>
                <artifactId>commons-fileupload</artifactId>
                <version>${commons.fileupload.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>${mybatis-plus-generator.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql-connector-j.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${alibaba.druid.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot3-starter</artifactId>
                <version>${durid.version}</version>
            </dependency>

            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson</artifactId>
                <version>${redission.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun.oss</groupId>
                <artifactId>aliyun-sdk-oss</artifactId>
                <version>${aliyun-oss.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>${excel.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>